### ISSUE TITLE
Crash on login after registration

### ISSUE THREAD

**Issue by rugged-bl** [inwords/InWords#68]
app start -> login -> registration (unsuccessful) -> login (successful) -> crash

```
2019-09-07 00:02:39.202 3900-3900/ru.inwords.inwords E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.inwords.inwords, PID: 3900
    java.lang.IllegalArgumentException: navigation destination ru.inwords.inwords:id/action_loginFragment_to_mainFragment_pop is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:789)
        at androidx.navigation.NavController.navigate(NavController.java:730)
        at androidx.navigation.NavController.navigate(NavController.java:716)
        at androidx.navigation.NavController.navigate(NavController.java:704)
        at ru.inwords.inwords.presentation.viewScenario.authorisation.login.LoginFragment.navigateOnSuccess(LoginFragment.kt:29)
        at ru.inwords.inwords.presentation.viewScenario.authorisation.SigningBaseFragment.renderSuccessState(SigningBaseFragment.kt:62)
        at ru.inwords.inwords.presentation.viewScenario.authorisation.SigningBaseFragment.processViewState(SigningBaseFragment.kt:80)
        at ru.inwords.inwords.presentation.viewScenario.authorisation.SigningBaseFragment.access$processViewState(SigningBaseFragment.kt:18)
        at ru.inwords.inwords.presentation.viewScenario.authorisation.SigningBaseFragment$onViewCreated$2.onChanged(SigningBaseFragment.kt:47)
        at ru.inwords.inwords.presentation.viewScenario.authorisation.SigningBaseFragment$onViewCreated$2.onChanged(SigningBaseFragment.kt:18)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by rugged-bl** [comment]
#61 related
